### ISSUE TITLE
Allow translate filter in notification-text

### ISSUE THREAD

**Issue by maelfrize** [tinesoft/ng-browser-update#1]
Would be great to put a translate filter in the notification  text. 

`<browser-update  
   notification-text="{{'HEADLINE' | translate}}">
</browser-update>`

http://angular-translate.github.io/docs/#/guide/04_using-translate-filter

**Comment by tinesoft** [comment]
Hi Mael,
That's a valid use case indeed!
I'll look into that pretty soon.

**Comment by maelfrize** [comment]
Perfect :+1: 

Thank you
