### ISSUE TITLE
Remove jQuery dependency 

### ISSUE THREAD

**Issue by maelfrize** [tinesoft/ng-browser-update#2]
Thanks for your library :) 

Any chances that you will remove the jquery dependency one day?

**Comment by tinesoft** [comment]
No problem, glad it helps!

Yep, the jQuery dependency is maybe extraneous for a small library like this... But as most angular projects included it by default, I didn't bother too much to remove it.

But you're right, it should get rid off.
I'll try to do that soon

**Comment by maelfrize** [comment]
Thanks so much for your quick fixes!

I will check them out soon.

**Comment by tinesoft** [comment]
No problem!
