### ISSUE TITLE
Installing using NPM fails

### ISSUE THREAD

**Issue by RobbertWolfs** [tinesoft/ng-browser-update#3]
npm install ng-browser-update

gives the following error: 

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng-browser-update"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ng-browser-update
npm ERR! 404
npm ERR! 404 'ng-browser-update' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robbertwolfs/git/pelckmans/pakket-p/npm-debug.log

**Comment by tinesoft** [comment]
Hi Robbert,

It seems to be an issue with the npm package. I'll look into that tonight.
In the meantime, can you try installing it with **bower** instead : 

`bower install ng-browser-update` ?

**Comment by RobbertWolfs** [comment]
We are not using bower in our project so I'll wait until tomorrow.
Thanks

**Comment by tinesoft** [comment]
It should be okay now!
